export const COUNTRY_LIST = [
  { id: 124, value: 'NZ', label: 'New Zealand' },
  { id: 8, value: 'AU', label: 'Australia' },
  { id: 183, value: 'GB', label: 'United Kingdom' },
  { id: 184, value: 'US', label: 'United States' },
  { id: 35, value: 'CN', label: 'China' },
  { id: 76, value: 'IN', label: 'India' },
  { id: 90, value: 'KR', label: 'South Korea' },
  { id: 84, value: 'JP', label: 'Japan' },
  { id: 146, value: 'WS', label: 'Samoa' },
  { id: 136, value: 'PH', label: 'Philippines' },
  { id: 0, value: 'AF', label: 'Afghanistan' },
  { id: 1, value: 'AL', label: 'Albania' },
  { id: 2, value: 'DZ', label: 'Algeria' },
  { id: 3, value: 'AD', label: 'Andorra' },
  { id: 4, value: 'AO', label: 'Angola' },
  { id: 5, value: 'AG', label: 'Antigua and Barbuda' },
  { id: 6, value: 'AR', label: 'Argentina' },
  { id: 7, value: 'AM', label: 'Armenia' },
  { id: 8, value: 'AU', label: 'Australia' },
  { id: 9, value: 'AT', label: 'Austria' },
  { id: 10, value: 'AZ', label: 'Azerbaijan' },
  { id: 11, value: 'BS', label: 'Bahamas' },
  { id: 12, value: 'BH', label: 'Bahrain' },
  { id: 13, value: 'BD', label: 'Bangladesh' },
  { id: 14, value: 'BB', label: 'Barbados' },
  { id: 15, value: 'BY', label: 'Belarus' },
  { id: 16, value: 'BE', label: 'Belgium' },
  { id: 17, value: 'BZ', label: 'Belize' },
  { id: 18, value: 'BJ', label: 'Benin' },
  { id: 19, value: 'BT', label: 'Bhutan' },
  { id: 20, value: 'BO', label: 'Bolivia' },
  { id: 21, value: 'BA', label: 'Bosnia and Herzegovina' },
  { id: 22, value: 'BW', label: 'Botswana' },
  { id: 23, value: 'BR', label: 'Brazil' },
  { id: 24, value: 'BN', label: 'Brunei' },
  { id: 25, value: 'BG', label: 'Bulgaria' },
  { id: 26, value: 'BF', label: 'Burkina Faso' },
  { id: 27, value: 'BI', label: 'Burundi' },
  { id: 28, value: 'CV', label: 'Cabo Verde' },
  { id: 29, value: 'KH', label: 'Cambodia' },
  { id: 30, value: 'CM', label: 'Cameroon' },
  { id: 31, value: 'CA', label: 'Canada' },
  { id: 32, value: 'CF', label: 'Central African Republic' },
  { id: 33, value: 'TD', label: 'Chad' },
  { id: 34, value: 'CL', label: 'Chile' },
  { id: 35, value: 'CN', label: 'China' },
  { id: 36, value: 'CO', label: 'Colombia' },
  { id: 37, value: 'KM', label: 'Comoros' },
  { id: 38, value: 'CG', label: 'Congo' },
  { id: 39, value: 'CD', label: 'Congo (DRC)' },
  { id: 40, value: 'CR', label: 'Costa Rica' },
  { id: 41, value: 'CI', label: 'Côte d’Ivoire' },
  { id: 42, value: 'HR', label: 'Croatia' },
  { id: 43, value: 'CU', label: 'Cuba' },
  { id: 44, value: 'CY', label: 'Cyprus' },
  { id: 45, value: 'CZ', label: 'Czech Republic' },
  { id: 46, value: 'DK', label: 'Denmark' },
  { id: 47, value: 'DJ', label: 'Djibouti' },
  { id: 48, value: 'DM', label: 'Dominica' },
  { id: 49, value: 'DO', label: 'Dominican Republic' },
  { id: 50, value: 'EC', label: 'Ecuador' },
  { id: 51, value: 'EG', label: 'Egypt' },
  { id: 52, value: 'SV', label: 'El Salvador' },
  { id: 53, value: 'GQ', label: 'Equatorial Guinea' },
  { id: 54, value: 'ER', label: 'Eritrea' },
  { id: 55, value: 'EE', label: 'Estonia' },
  { id: 56, value: 'SZ', label: 'Eswatini' },
  { id: 57, value: 'ET', label: 'Ethiopia' },
  { id: 58, value: 'FJ', label: 'Fiji' },
  { id: 59, value: 'FI', label: 'Finland' },
  { id: 60, value: 'FR', label: 'France' },
  { id: 61, value: 'GA', label: 'Gabon' },
  { id: 62, value: 'GM', label: 'Gambia' },
  { id: 63, value: 'GE', label: 'Georgia' },
  { id: 64, value: 'DE', label: 'Germany' },
  { id: 65, value: 'GH', label: 'Ghana' },
  { id: 66, value: 'GR', label: 'Greece' },
  { id: 67, value: 'GD', label: 'Grenada' },
  { id: 68, value: 'GT', label: 'Guatemala' },
  { id: 69, value: 'GN', label: 'Guinea' },
  { id: 70, value: 'GW', label: 'Guinea-Bissau' },
  { id: 71, value: 'GY', label: 'Guyana' },
  { id: 72, value: 'HT', label: 'Haiti' },
  { id: 73, value: 'HN', label: 'Honduras' },
  { id: 74, value: 'HU', label: 'Hungary' },
  { id: 75, value: 'IS', label: 'Iceland' },
  { id: 76, value: 'IN', label: 'India' },
  { id: 77, value: 'ID', label: 'Indonesia' },
  { id: 78, value: 'IR', label: 'Iran' },
  { id: 79, value: 'IQ', label: 'Iraq' },
  { id: 80, value: 'IE', label: 'Ireland' },
  { id: 81, value: 'IL', label: 'Israel' },
  { id: 82, value: 'IT', label: 'Italy' },
  { id: 83, value: 'JM', label: 'Jamaica' },
  { id: 84, value: 'JP', label: 'Japan' },
  { id: 85, value: 'JO', label: 'Jordan' },
  { id: 86, value: 'KZ', label: 'Kazakhstan' },
  { id: 87, value: 'KE', label: 'Kenya' },
  { id: 88, value: 'KI', label: 'Kiribati' },
  { id: 89, value: 'KP', label: 'North Korea' },
  { id: 90, value: 'KR', label: 'South Korea' },
  { id: 91, value: 'KW', label: 'Kuwait' },
  { id: 92, value: 'KG', label: 'Kyrgyzstan' },
  { id: 93, value: 'LA', label: 'Laos' },
  { id: 94, value: 'LV', label: 'Latvia' },
  { id: 95, value: 'LB', label: 'Lebanon' },
  { id: 96, value: 'LS', label: 'Lesotho' },
  { id: 97, value: 'LR', label: 'Liberia' },
  { id: 98, value: 'LY', label: 'Libya' },
  { id: 99, value: 'LI', label: 'Liechtenstein' },
  { id: 100, value: 'LT', label: 'Lithuania' },
  { id: 101, value: 'LU', label: 'Luxembourg' },
  { id: 102, value: 'MG', label: 'Madagascar' },
  { id: 103, value: 'MW', label: 'Malawi' },
  { id: 104, value: 'MY', label: 'Malaysia' },
  { id: 105, value: 'MV', label: 'Maldives' },
  { id: 106, value: 'ML', label: 'Mali' },
  { id: 107, value: 'MT', label: 'Malta' },
  { id: 108, value: 'MH', label: 'Marshall Islands' },
  { id: 109, value: 'MR', label: 'Mauritania' },
  { id: 110, value: 'MU', label: 'Mauritius' },
  { id: 111, value: 'MX', label: 'Mexico' },
  { id: 112, value: 'FM', label: 'Micronesia' },
  { id: 113, value: 'MD', label: 'Moldova' },
  { id: 114, value: 'MC', label: 'Monaco' },
  { id: 115, value: 'MN', label: 'Mongolia' },
  { id: 116, value: 'ME', label: 'Montenegro' },
  { id: 117, value: 'MA', label: 'Morocco' },
  { id: 118, value: 'MZ', label: 'Mozambique' },
  { id: 119, value: 'MM', label: 'Myanmar' },
  { id: 120, value: 'NA', label: 'Namibia' },
  { id: 121, value: 'NR', label: 'Nauru' },
  { id: 122, value: 'NP', label: 'Nepal' },
  { id: 123, value: 'NL', label: 'Netherlands' },
  { id: 124, value: 'NZ', label: 'New Zealand' },
  { id: 125, value: 'NI', label: 'Nicaragua' },
  { id: 126, value: 'NE', label: 'Niger' },
  { id: 127, value: 'NG', label: 'Nigeria' },
  { id: 128, value: 'NO', label: 'Norway' },
  { id: 129, value: 'OM', label: 'Oman' },
  { id: 130, value: 'PK', label: 'Pakistan' },
  { id: 131, value: 'PW', label: 'Palau' },
  { id: 132, value: 'PA', label: 'Panama' },
  { id: 133, value: 'PG', label: 'Papua New Guinea' },
  { id: 134, value: 'PY', label: 'Paraguay' },
  { id: 135, value: 'PE', label: 'Peru' },
  { id: 136, value: 'PH', label: 'Philippines' },
  { id: 137, value: 'PL', label: 'Poland' },
  { id: 138, value: 'PT', label: 'Portugal' },
  { id: 139, value: 'QA', label: 'Qatar' },
  { id: 140, value: 'RO', label: 'Romania' },
  { id: 141, value: 'RU', label: 'Russia' },
  { id: 142, value: 'RW', label: 'Rwanda' },
  { id: 143, value: 'KN', label: 'Saint Kitts and Nevis' },
  { id: 144, value: 'LC', label: 'Saint Lucia' },
  { id: 145, value: 'VC', label: 'Saint Vincent and the Grenadines' },
  { id: 146, value: 'WS', label: 'Samoa' },
  { id: 147, value: 'SM', label: 'San Marino' },
  { id: 148, value: 'ST', label: 'Sao Tome and Principe' },
  { id: 149, value: 'SA', label: 'Saudi Arabia' },
  { id: 150, value: 'SN', label: 'Senegal' },
  { id: 151, value: 'RS', label: 'Serbia' },
  { id: 152, value: 'SC', label: 'Seychelles' },
  { id: 153, value: 'SL', label: 'Sierra Leone' },
  { id: 154, value: 'SG', label: 'Singapore' },
  { id: 155, value: 'SK', label: 'Slovakia' },
  { id: 156, value: 'SI', label: 'Slovenia' },
  { id: 157, value: 'SB', label: 'Solomon Islands' },
  { id: 158, value: 'SO', label: 'Somalia' },
  { id: 159, value: 'ZA', label: 'South Africa' },
  { id: 160, value: 'SS', label: 'South Sudan' },
  { id: 161, value: 'ES', label: 'Spain' },
  { id: 162, value: 'LK', label: 'Sri Lanka' },
  { id: 163, value: 'SD', label: 'Sudan' },
  { id: 164, value: 'SR', label: 'Suriname' },
  { id: 165, value: 'SE', label: 'Sweden' },
  { id: 166, value: 'CH', label: 'Switzerland' },
  { id: 167, value: 'SY', label: 'Syria' },
  { id: 168, value: 'TW', label: 'Taiwan' },
  { id: 169, value: 'TJ', label: 'Tajikistan' },
  { id: 170, value: 'TZ', label: 'Tanzania' },
  { id: 171, value: 'TH', label: 'Thailand' },
  { id: 172, value: 'TL', label: 'Timor-Leste' },
  { id: 173, value: 'TG', label: 'Togo' },
  { id: 174, value: 'TO', label: 'Tonga' },
  { id: 175, value: 'TT', label: 'Trinidad and Tobago' },
  { id: 176, value: 'TN', label: 'Tunisia' },
  { id: 177, value: 'TR', label: 'Turkey' },
  { id: 178, value: 'TM', label: 'Turkmenistan' },
  { id: 179, value: 'TV', label: 'Tuvalu' },
  { id: 180, value: 'UG', label: 'Uganda' },
  { id: 181, value: 'UA', label: 'Ukraine' },
  { id: 182, value: 'AE', label: 'United Arab Emirates' },
  { id: 183, value: 'GB', label: 'United Kingdom' },
  { id: 184, value: 'US', label: 'United States' },
  { id: 185, value: 'UY', label: 'Uruguay' },
  { id: 186, value: 'UZ', label: 'Uzbekistan' },
  { id: 187, value: 'VU', label: 'Vanuatu' },
  { id: 188, value: 'VE', label: 'Venezuela' },
  { id: 189, value: 'VN', label: 'Vietnam' },
  { id: 190, value: 'YE', label: 'Yemen' },
  { id: 191, value: 'ZM', label: 'Zambia' },
  { id: 192, value: 'ZW', label: 'Zimbabwe' },
];
