apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  db-connection-string: "DB_CONNECTION_STRING"
  openai-api-key: "OPENAI_API_KEY"
  firebase-credentials: "FIREBASE_SERVICE_ACCOUNT_JSON"